//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landtory.Engine {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Landtory.Engine.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The suspect was apprehended. 的本地化字符串。
        /// </summary>
        internal static string Apprehended {
            get {
                return ResourceManager.GetString("Apprehended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~r~Failed to arrest suspect. 的本地化字符串。
        /// </summary>
        internal static string ArrestException {
            get {
                return ResourceManager.GetString("ArrestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~r~Arrest Failed. 的本地化字符串。
        /// </summary>
        internal static string FailedToArrest {
            get {
                return ResourceManager.GetString("FailedToArrest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~r~Fatal Error during Arrest. 的本地化字符串。
        /// </summary>
        internal static string FatalErrorArr {
            get {
                return ResourceManager.GetString("FatalErrorArr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~r~You cannot arrest multiple suspect at once. 的本地化字符串。
        /// </summary>
        internal static string MultipleSuspectArrestAttmept {
            get {
                return ResourceManager.GetString("MultipleSuspectArrestAttmept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to Landtory. Go to Goldberg &amp; Shyster to get on duty. 的本地化字符串。
        /// </summary>
        internal static string OnDuty {
            get {
                return ResourceManager.GetString("OnDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are now onduty as a police officer. 的本地化字符串。
        /// </summary>
        internal static string OnDutyNow {
            get {
                return ResourceManager.GetString("OnDutyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~r~You need a vehicle to switch Siren without Driver. 的本地化字符串。
        /// </summary>
        internal static string SirenDriverNoVehicle {
            get {
                return ResourceManager.GetString("SirenDriverNoVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Siren Without Driver Off 的本地化字符串。
        /// </summary>
        internal static string SirenWithoutDriverOff {
            get {
                return ResourceManager.GetString("SirenWithoutDriverOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Siren Without Driver On 的本地化字符串。
        /// </summary>
        internal static string SirenWithoutDriverOn {
            get {
                return ResourceManager.GetString("SirenWithoutDriverOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must stand close to suspect to arrest. 的本地化字符串。
        /// </summary>
        internal static string StandClose {
            get {
                return ResourceManager.GetString("StandClose", resourceCulture);
            }
        }
    }
}
